### ISSUE TITLE
Another Dividend Parsing Error

### ISSUE THREAD

**Issue by bwurxsolutions** [sstrickx/yahoofinance-api#10]
Using 1.2.2. I know this issue has been logged a couple of times, but found another format that can't be parsed. Getting "MSFT". Something is strange with the response...
INFO: Sending request: http://finance.yahoo.com/d/quotes.csv?s=MSFT&f=n0sc4x0a0b2sa5sb0b3sb6sl1sk3sd1t1o0p0g0h0v0a2k0j0m3m4sj2sss1sj1sf6sr1q0d0y0e0e7e9e8r0r5p6p5b4s6j4t8&e=.csv

INFO: Parsing CSV line: N/A,\"MSFT\",\"USD\",N/A,N/A,N/A,\"MSFT\",4000,\"MSFT\",N/A,N/A,\"MSFT\",5500,\"MSFT\",42.62,\"MSFT\",190,\"MSFT\",\"3/9/2015\",\"12:31pm\",N/A,N/A,N/A,N/A,N/A,36259900,N/A,N/A,43.54,45.86,\"MSFT\",8203785000,\"MSFT\",\"MSFT\",N/A,\"MSFT\",349.65B,\"MSFT\",7564218000,\"MSFT\",\"3/12/2015\",N/A,N/A,N/A,N/A,2.40,0.63,2.93,N/A,2.20,3.79,3.72,11.18,93.46B,33.61B,47.81
Mar 09, 2015 9:46:07 AM yahoofinance.Utils parseDividendDate
SEVERE: Unparseable date: "3/12/2015"

Also what is strange is that the company name is not be returned from the API...something appears to be broken on the Yahoo side. Thanks

**Comment by sstrickx** [comment]
Hi,

Thanks for reporting those date issues. Please don't hesitate to report them as this is the only way I can fix all of them.

It seems that most of the time Yahoo Finance is returning the full info on MSFT, but from time to time I also get the response with a lot of data missing - mostly when you do two requests right after eachother.

Please make sure to not do something like in the following example. You would be sending twice the same request to Yahoo Finance in a matter of milliseconds - which will not give you any benefit.
```java
Stock stock = YahooFinance.get("MSFT");
stock.getQuote(true)
```
The `true` parameter passed to the `getQuote` method will cause a new request to Yahoo Finance right after the `YahooFinance.get` method already sent one. This makes sense when you want to update the quote after several seconds / minutes, but not right after having just requested a quote with the `YahooFinance.get` method.
