### ISSUE TITLE
Bombay tickers

### ISSUE THREAD

**Issue by peternees** [sstrickx/yahoofinance-api#103]
I thinks it's not possible, but I can ask: is there a means to get price info for Bombay. Sample ticker: TCI.BO

**Comment by sstrickx** [comment]
I fear you are right. All values returned from stocks on the BSE seem to be empty, except from EPS, which I honestly wouldn't trust too much.

**Comment by sstrickx** [comment]
It looks like this information will actually be available after the update that fixes #105.
