### ISSUE TITLE
Maven repo

### ISSUE THREAD

**Issue by Avec112** [sstrickx/yahoofinance-api#11]
Great API you have made there :+1: 

I think however this api should be made available from maven repository. It is kind a hard to include in a project today when you do not have your own local repository.

**Comment by sstrickx** [comment]
Thanks! 
Will take a few days to get everything ready and approved. I'll work on it.

**Comment by sstrickx** [comment]
Small update: everything is ready to be deployed to the central maven repository, just waiting for the final approval from Sonatype (should take 2 business days max).

**Comment by sstrickx** [comment]
Hi,

The project should now be available on the Maven Central Repository.

```xml
<dependency>
    <groupId>com.yahoofinance-api</groupId>
    <artifactId>YahooFinanceAPI</artifactId>
    <version>x.y.z</version>
</dependency>
```

**Comment by Avec112** [comment]
Cool, thx :+1:
