### ISSUE TITLE
character set

### ISSUE THREAD

**Issue by peternees** [sstrickx/yahoofinance-api#111]
Anybody knows which character set is used for the stock name? I has now special characters that wheren't there with the previous api.

**Comment by sstrickx** [comment]
Could you provide an example?

**Comment by peternees** [comment]
SII.PA
I get this: SII (Soci��t�� pour l'Informatique Industrielle) Soci��t�� Anonyme

I would try to solve it with new String(stock.getName().getBytes, chasetName);

**Comment by sstrickx** [comment]
I would suggest giving it a try with UTF-8.

**Comment by peternees** [comment]
I tried, but doesn't work: SII (Soci??t?? pour l'Informatique Industrielle) Soci??t?? Anonyme

**Comment by peternees** [comment]
Problem is solved. It was a problem with my own environment.
