### ISSUE TITLE
null objects when using stock.getHistory method

### ISSUE THREAD

**Issue by kejuntong** [sstrickx/yahoofinance-api#112]
Hi,

I encountered an issue that when using stock.getHistory for specific stock such as "NVDA", it returned a lot of null objects in the list. Here is the code:
--------------------------------------------------------------------------------------------------------
                    Stock stock = YahooFinance.get("NVDA", true);
                    Calendar calendarFrom = Calendar.getInstance();
                    calendarFrom.add(Calendar.MONTH, -2);
                    calendarFrom.set(Calendar.DATE, 1);
                    Calendar calendarTo = Calendar.getInstance();
                    List<HistoricalQuote> list = stock.getHistory(calendarFrom, calendarTo, Interval.DAILY);
--------------------------------------------------------------------------------------------------------

Here is the result of the list:
--------------------------------------------------------------------------------------------------------
0 = {HistoricalQuote@6990} "NVDA@2017-09-01: 169.600006-171.899994, 169.949997->170.460007 (170.460007)"
1 = {HistoricalQuote@6991} "NVDA@2017-09-05: 163.559998-168.580002, 168.380005->165.910004 (165.910004)"
2 = {HistoricalQuote@6992} "NVDA@2017-09-06: 164.399994-167.800003, 167.240005->165.809998 (165.809998)"
3 = {HistoricalQuote@6993} "NVDA@2017-09-07: 164.949997-167.889999, 166.490005->166.580002 (166.580002)"
4 = {HistoricalQuote@6994} "NVDA@2017-09-08: 162.710007-166.710007, 166.110001->163.690002 (163.690002)"
5 = {HistoricalQuote@6995} "NVDA@2017-09-11: 165.320007-169.429993, 165.539993->169.000000 (169.000000)"
6 = {HistoricalQuote@6996} "NVDA@2017-09-12: 166.970001-170.000000, 170.000000->169.610001 (169.610001)"
7 = {HistoricalQuote@6997} "NVDA@2017-09-13: 167.279999-171.539993, 168.589996->170.369995 (170.369995)"
8 = {HistoricalQuote@6998} "NVDA@2017-09-14: 167.800003-172.559998, 168.789993->169.399994 (169.399994)"
9 = {HistoricalQuote@6999} "NVDA@2017-09-15: 172.649994-180.110001, 172.860001->180.110001 (180.110001)"
10 = {HistoricalQuote@7000} "NVDA@2017-09-18: 184.860001-191.199997, 185.139999->187.550003 (187.550003)"
11 = {HistoricalQuote@7001} "NVDA@2017-09-19: 184.619995-189.850006, 185.509995->187.350006 (187.350006)"
12 = {HistoricalQuote@7002} "NVDA@2017-09-20: 184.210007-189.419998, 187.500000->185.839996 (185.839996)"
13 = {HistoricalQuote@7003} "NVDA@2017-09-21: 177.610001-182.699997, 181.639999->180.759995 (180.759995)"
14 = {HistoricalQuote@7004} "NVDA@2017-09-22: 178.600006-182.309998, 180.300003->179.000000 (179.000000)"
15 = {HistoricalQuote@7005} "NVDA@2017-09-25: 170.160004-177.800003, 177.750000->171.000000 (171.000000)"
16 = {HistoricalQuote@7006} "NVDA@2017-09-26: 170.350006-178.679993, 176.449997->171.960007 (171.960007)"
17 = {HistoricalQuote@7007} "NVDA@2017-09-27: 172.750000-176.270004, 175.619995->175.729996 (175.729996)"
18 = {HistoricalQuote@7008} "NVDA@2017-09-28: 173.759995-176.179993, 176.020004->175.679993 (175.679993)"
19 = {HistoricalQuote@7009} "NVDA@2017-09-29: 177.250000-179.729996, 179.080002->178.770004 (178.770004)"
20 = {HistoricalQuote@7010} "NVDA@2017-10-02: 177.000000-181.979996, 180.800003->179.000000 (179.000000)"
21 = {HistoricalQuote@7011} "NVDA@2017-10-03: 177.580002-180.580002, 179.250000->179.369995 (179.369995)"
22 = {HistoricalQuote@7012} "NVDA@2017-10-04: 178.139999-181.770004, 179.619995->180.869995 (180.869995)"
23 = {HistoricalQuote@7013} "NVDA@2017-10-05: 179.559998-182.000000, 181.860001->180.770004 (180.770004)"
24 = {HistoricalQuote@7014} "NVDA@2017-10-06: 179.000000-181.839996, 179.649994->181.300003 (181.300003)"
25 = {HistoricalQuote@7015} "NVDA@2017-10-09: 182.029999-186.729996, 182.789993->185.389999 (185.389999)"
26 = {HistoricalQuote@7016} "NVDA@2017-10-10: 187.259995-192.949997, 191.429993->188.929993 (188.929993)"
27 = {HistoricalQuote@7017} "NVDA@2017-10-11: 187.740005-191.000000, 189.600006->190.940002 (190.940002)"
28 = {HistoricalQuote@7018} "NVDA@2017-10-12: 189.929993-193.089996, 191.080002->191.029999 (191.029999)"
29 = {HistoricalQuote@7019} "NVDA@2017-10-13: 191.649994-195.000000, 193.550003->194.589996 (194.589996)"
**30 = {HistoricalQuote@7020} "NVDA@2017-10-16: null-null, null->null (null)"
31 = {HistoricalQuote@7021} "NVDA@2017-10-17: null-null, null->null (null)"
32 = {HistoricalQuote@7022} "NVDA@2017-10-18: null-null, null->null (null)"
33 = {HistoricalQuote@7023} "NVDA@2017-10-19: null-null, null->null (null)"
34 = {HistoricalQuote@7024} "NVDA@2017-10-20: null-null, null->null (null)"
35 = {HistoricalQuote@7025} "NVDA@2017-10-23: null-null, null->null (null)"
36 = {HistoricalQuote@7026} "NVDA@2017-10-24: null-null, null->null (null)"
37 = {HistoricalQuote@7027} "NVDA@2017-10-25: null-null, null->null (null)"
38 = {HistoricalQuote@7028} "NVDA@2017-10-26: null-null, null->null (null)"
39 = {HistoricalQuote@7029} "NVDA@2017-10-27: null-null, null->null (null)"
40 = {HistoricalQuote@7030} "NVDA@2017-10-30: null-null, null->null (null)"
41 = {HistoricalQuote@7031} "NVDA@2017-10-31: null-null, null->null (null)"
42 = {HistoricalQuote@7032} "NVDA@2017-11-01: null-null, null->null (null)"
43 = {HistoricalQuote@7033} "NVDA@2017-11-02: null-null, null->null (null)"**
44 = {HistoricalQuote@7034} "NVDA@2017-11-03: 205.339996-208.690002, 207.199997->208.690002 (208.690002)"
45 = {HistoricalQuote@7035} "NVDA@2017-11-06: 206.699997-209.979996, 207.199997->209.630005 (209.630005)"
46 = {HistoricalQuote@7036} "NVDA@2017-11-07: 210.059998-212.899994, 210.550003->212.029999 (212.029999)"
47 = {HistoricalQuote@7037} "NVDA@2017-11-08: 207.240005-212.000000, 211.850006->209.160004 (209.160004)"
48 = {HistoricalQuote@7038} "NVDA@2017-11-09: 200.369995-206.330002, 205.270004->205.320007 (205.320007)"
49 = {HistoricalQuote@7039} "NVDA@2017-11-10: 211.630005-218.669998, 213.080002->216.139999 (216.139999)"
50 = {HistoricalQuote@7040} "NVDA@2017-11-13: 212.009995-217.169998, 216.139999->212.630005 (212.630005)"
--------------------------------------------------------------------------------------------------------

**Comment by sstrickx** [comment]
Hi, I can't reproduce the issue.
Seems like YahooFinance might be sending back some null values for specific dates at random. (or there was an issue on their side at the time you made the request)
There's not much we can do about that.
We could possibly not include those dates in the returned list, but that way it might be less clear something went wrong with the answer from YahooFinance.

**Comment by kejuntong** [comment]
@sstrickx Thank you for taking time to investigate :)
