### ISSUE TITLE
Some non US stocks have no dividend yield information

### ISSUE THREAD

**Issue by vadimjouk** [sstrickx/yahoofinance-api#115]
Some non US stocks have no dividend yield information, for example 
IFX.DE
BPE5.DE
RDSA.AS
This is becouse you returns empty StockDividend if dividendDate is missing, but trailingAnnualDividendRate and trailingAnnualDividendYield are presented, please fill this values in StockDividend object

**Comment by vadimjouk** [comment]
I fixed this and created a Pull request

**Comment by vadimjouk** [comment]
Great, thanks!

**Comment by sstrickx** [comment]
Now released in 3.12.3
