### ISSUE TITLE
yahoo finance api deprecated

### ISSUE THREAD

**Issue by Sridharc20** [sstrickx/yahoofinance-api#118]
Hi Team,
Got an error in my application:
https://ichart.yahoo.com/table.csv?s=GOOG&a=10&b=28&c=2016&d=10&e=28&f=2017&g=m&ignore=.csv
2017-11-28 15:55:34.183 ERROR 14992 --- [nio-8301-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.net.UnknownHostException: ichart.yahoo.com

It seems, Yahoo team is deprecating the finance APIs.

**Comment by sstrickx** [comment]
Hi, please try using the latest version of this library (3.12.3)

**Comment by Sridharc20** [comment]
I've tried to use the latest version too.

<dependency>
<groupId>com.yahoofinance-api</groupId>
<artifactId>YahooFinanceAPI</artifactId>
<version>3.12.3</version>
</dependency>

**Comment by sstrickx** [comment]
Please post a code snippet and the logs that you get.

**Comment by sstrickx** [comment]
Just noticed you updated the issue. Those logs are definitely from an older version, or you're using the library in a different way than intended (code snippet would be useful in that case).

**Comment by Sridharc20** [comment]
Hi Sir, 
Thanks much. Apologies, my code was using older version. After upgrading to the latest version, i'm getting the stock data. 

Thanks,
Sridhar C
