### ISSUE TITLE
JsonParseException

### ISSUE THREAD

**Issue by peternees** [sstrickx/yahoofinance-api#119]
I notice quite a lot of the following exceptions in my log:
YahooFinance: [Ljava.lang.String;@4e24214d com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null') (YahooConnector.java:37) at [Source: (InputStreamReader); line: 1, column: 2]

I have the impression it happens only when requesting a set of symbols.
If I rerun the same query later it's ok. Any idea of the cause?

**Comment by sstrickx** [comment]
It would be nice to have a more specific example. I've never seen this exception and can't manage to reproduce it. It would help a lot to include the part of the log where it prints the request. For example: `[main] INFO yahoofinance.quotes.query1v7.QuotesRequest - Sending request: https://query1.finance.yahoo.com/v7/finance/quote?symbols=INTC%2CTSLA%2CFB%2CGOOG`
