### ISSUE TITLE
Returns NULL pointer instead of the looked up symbol on single-symbol get...

### ISSUE THREAD

**Issue by Tronmech** [sstrickx/yahoofinance-api#12]
StockQuotesRequest.parseCSVLine() will scramble the stock symbol if the first token isn't (Stock name) isn't enclosed in quotes -- and it currently isn't.

A quick and dirty kludge was to do this:
        int pos1 = 0;
        int pos2 = 0;
        if (line.startsWith("\""))
        {
            pos1 = 1; // skip first \"
            pos2 = line.indexOf('\"', 1);
        }
        else
        {
            pos1 = 0;
            pos2 = line.indexOf(",", pos1);
        }

and:
String symbol = fullSymbol.substring(1, fullSymbol.length() - 1);
becomes
String symbol = fullSymbol.substring(0, fullSymbol.length() - 1);

**Comment by sstrickx** [comment]
Hi,

Could you give me an example where this is the case? For all the ones I tried it is actually enclosed in quotes.

**Comment by sstrickx** [comment]
Nevermind, I was able to reproduce the issue... It's a bit strange though, Yahoo Finance is currently returning incomplete results for everything. Will need to check that out.
I applied your fix (with minor adjustments) and it seems to help, a new version will be supplied soon. Thanks!

**Comment by hillarys92** [comment]
I am also getting NullPointerExceptions with every request. Do you have any idea of when or how this might be fixed? I am using this API in my Final Year Project in College and my demonstration is soon!
From stepping through the program in the debugger it seems that the stock that get returned from the YahooFinance.get(symbol) method call will return null regardless of the symbol being searched for

**Comment by sstrickx** [comment]
Yahoo has apparently changed some of the property names used in the request. I'm currently working on discovering the new values. I'll do my best to deliver a fix today.
