### ISSUE TITLE
EBITDA and other statistics are not populated

### ISSUE THREAD

**Issue by poitzl** [sstrickx/yahoofinance-api#121]
When you call [StockStats].getEBITDA you return always null;

For IBM there is a EBITDA on yahoo's homepage. Is the value wrongly populated due to the fact that the value is given in billions (EBITDA = 16.84B)?

see you
Paul

**Comment by sstrickx** [comment]
Hi, EBITDA is no longer provided through the endpoint that we're currently connecting to (https://query1.finance.yahoo.com/v7). The previous endpoint was stopped by Yahoo.

**Comment by peternees** [comment]
same with stats.getSharesFloat()?
