### ISSUE TITLE
Stock Symbol Lookup

### ISSUE THREAD

**Issue by mnemotron** [sstrickx/yahoofinance-api#123]
Hi,
I use your API for my asset performance tool ["REVENUE"](https://github.com/mnemotron/Revenue).
I have already successfully integrated your API, historical data of a share is already displayed.

So, what else I need is a stock symbol lookup interface.
Can you include the functionality in your API?
I can support you, when you add me as contributor.

Here are two examples:

Yahoo Finance API e.g. 1:
**URL:**

> http://d.yimg.com/aq/autoc?query=bmw&region=DE&lang=en-US&callback=YAHOO.util.ScriptNodeDataSource.callbacks

**RESULT:**

> YAHOO.util.ScriptNodeDataSource.callbacks({"ResultSet":{"Query":"bmw","Result":[{"symbol":"BMW.TI","name":"BMW","exch":"TLO","type":"S","exchDisp":"TLX Exchange","typeDisp":"Equity"},{"symbol":"BMW.DE","name":"Bayerische Motoren Werke Aktiengesellschaft","exch":"GER","type":"S","exchDisp":"XETRA","typeDisp":"Equity"},{"symbol":"BMWYY","name":"Bayerische Motoren Werke Aktiengesellschaft","exch":"PNK","type":"S","exchDisp":"OTC Markets","typeDisp":"Equity"},{"symbol":"BMW.F","name":"Bayerische Motoren Werke Aktiengesellschaft","exch":"FRA","type":"S","exchDisp":"Frankfurt","typeDisp":"Equity"},{"symbol":"BMW3.F","name":"Bayerische Motoren Werke Aktiengesellschaft","exch":"FRA","type":"S","exchDisp":"Frankfurt","typeDisp":"Equity"},{"symbol":"BMW3.DE","name":"Bayerische Motoren Werke Aktiengesellschaft","exch":"GER","type":"S","exchDisp":"XETRA","typeDisp":"Equity"},{"symbol":"BMW.BE","name":"BAY.MOTOREN WERKE AG ST","exch":"BER","type":"S","exchDisp":"Berlin","typeDisp":"Equity"},{"symbol":"BMW3.TI","name":"BMW PREF","exch":"TLO","type":"S","exchDisp":"TLX Exchange","typeDisp":"Equity"},{"symbol":"BMW3.SG","name":"BAYERISCHE MOTOREN WERKE AG VOR","exch":"STU","type":"S","exchDisp":"Stuttgart","typeDisp":"Equity"},{"symbol":"BMW.DU","name":"BAY.MOTOREN WERKE AG ST","exch":"DUS","type":"S","exchDisp":"Dusseldorf Stock Exchange","typeDisp":"Equity"}]}});

Yahoo Finance API e.g. 2:
http://autoc.finance.yahoo.com/autoc?query=alphabet&region=EU&lang=en-GB

An C# implementation example:
http://www.jarloo.com/yahoo-stock-symbol-lookup/

Thanx. Mnemotron.

**Comment by sstrickx** [comment]
I'm sorry. I don't believe symbol lookup should be part of the API.
