### ISSUE TITLE
Does this still work

### ISSUE THREAD

**Issue by JamesBarnes88** [sstrickx/yahoofinance-api#124]
Yahoo shut down their apis on Nov 2, 2017. Does this repo still function?

I'm getting this error: `java.net.UnknownHostException: download.finance.yahoo.com`

**Comment by sstrickx** [comment]
Please use the latest version of the library (3.12.3).

**Comment by girishgodage** [comment]
<dependency>
			<groupId>com.yahoofinance-api</groupId>
			<artifactId>YahooFinanceAPI</artifactId>
			<version>3.13.0</version>
		</dependency>
