### ISSUE TITLE
java.net.ProtocolException: Server redirected too many  times

### ISSUE THREAD

**Issue by oursgamemf** [sstrickx/yahoofinance-api#126]
Code raise this exception when:
 YahooFinance.get(nameTk, from, to, Interval.MONTHLY);
is called.
Any ideas?

**Comment by gomeratrab** [comment]
I get the same error when executing the last example from the website (or any example including historical data).

**Comment by kongeb** [comment]
Same thing here. Any idea what the issue is?

**Comment by emanueleg** [comment]
add the line 
`CookieHandler.setDefault(new CookieManager(null, CookiePolicy.ACCEPT_ALL));`
at the beginning of your code - should make your code work again
