### ISSUE TITLE
Add ability to download only specific quote fields

### ISSUE THREAD

**Issue by matoos32** [sstrickx/yahoofinance-api#127]
Hi there,

Great library! This is an enhancement request to support downloading only those fields in a quote that are really desired. For example not the the entire "basic quote" but select data like only open, high, low, last price. This would minimize bandwidth and increase overall application speed.

Maybe an API call like below, but there might be a better way:

`public static Map<String, Stock> get(String[] symbols, QuoteField[] fields) throws IOException`

Where `QuoteField[]` is an array of enum values representing the desired. Could also use a bit mask instead of this array.

Example:

`Map<String, Stock> quote = YahooFinance.get(symbols, fields);`

Then maybe getters for fields that weren't downloaded would return `null` but then you'd need null checks in client code for robustness.

An alternative could be to define a family of predefined download configurations beyond the "basic quote" and there would be no need to specify the desired fields. For example:

* OHLPV (only: open, high, low, last price, volume)
* Fundamentals (only: dividend, eps, etc.)
* etc.

Thanks for your consideration!

**Comment by sstrickx** [comment]
Thanks for the suggestion. However, with the way that the Yahoo Finance API works these days, that doesn't make much sense anymore. 
It's not possible to limit the number of returned fields in the request, so we always get the full json with all data inside. 
There's no benefit to then not just store all the received information in the object.
