### ISSUE TITLE
Support for after hours trading (Pre / Post Market)

### ISSUE THREAD

**Issue by spew** [sstrickx/yahoofinance-api#128]
The Yahoo query1/v7 API supports giving out pre & post market after hours trading data. The java library should make this available to consumers.

**Comment by spew** [comment]
Note, I can pick this up, one issue I'm running into is that the tests are all built around what appears to be a legacy CSV based API? 

I am adding support for using the query1/v7 json responses as test data sources. Does this sound reasonable?

**Comment by sstrickx** [comment]
Thanks for the pull request! To be handled with version 4.0.0.
