### ISSUE TITLE
How to get the change in stock share

### ISSUE THREAD

**Issue by SilverFoxA** [sstrickx/yahoofinance-api#13]
Sir, thank you for writing this library. 
The problem that i am facing currently is how get the change in stock price and how to know whether it's in negative or positive?

**Comment by sstrickx** [comment]
Hi,

That should be pretty easy with the [`StockQuote.getChange()`](http://yahoofinance-api.com/javadoc/yahoofinance/quotes/stock/StockQuote.html#getChange--) method.
This will return a BigDecimal with the difference between the previous close and the current price. The number will be negative if the current price is lower than the previous close and positive if the current price is higher.

For example:
```java
Stock stock = YahooFinance.get("GOOG");
StockQuote quote = stock.getQuote();
BigDecimal change = quote.getChange();
```

You can also retrieve the relative change compared to the previous close:
```java
Stock stock = YahooFinance.get("INTC");
BigDecimal change = stock.getQuote().getChangeInPercent();
```

Check out the JavaDoc at http://yahoofinance-api.com/javadoc/yahoofinance/YahooFinance.html

Please let me know if this answers your question.

**Comment by SilverFoxA** [comment]
Sir, the `stock.getname()` method is always returning null, isn't it suppose to return the name of the company

**Comment by sstrickx** [comment]
Yes it should. This could mean that you're using the wrong symbol, or that there's a bug in the API.
Could you provide me with an example where it's returning `null`? (or just the symbol of the stock where you encounter this issue should be fine as well)

**Comment by SilverFoxA** [comment]
Sir, I am trying to use an `arraylist` with the following fields 
    
    array.add(0, "GOOG");
        array.add(1, "INTC");
and I'm calling them as
       
     Stock stock = YahooFinance.get(items.get(position));
When i debug for the `stock` value i do see the `name`` symbol ` everything but when i try to populate those fields with a `textview` it returns null

     tv1.setText(String.valueOf(stock.getName()));

**Comment by sstrickx** [comment]
It seems to work fine on my end. Do you have the name of the stock when you print it?
```java
System.out.println(stock.getName());
```
From what you've shown it's not really possible to find out what's going wrong. Please post a full example that you think should be working but isn't.

**Comment by SilverFoxA** [comment]
Sir, here is the complete code that i have 

    public class CustomStockListAdapter extends ArrayAdapter<String> {
    LayoutInflater inflater;
    TextView tv1, change, symbol, company;
    public ArrayList<String> items;

    public CustomStockListAdapter(Activity activity, int resource, ArrayList<String> objects) {
        super(activity, resource, objects);
        inflater = activity.getWindow().getLayoutInflater();
        this.items = objects;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        View view = inflater.inflate(R.layout.stock_ticker, parent, false);
        tv1 = (TextView) view.findViewById(R.id.stockValue);
        change = (TextView) view.findViewById(R.id.stockchange);
        symbol = (TextView) view.findViewById(R.id.tickersymbol);
        company = (TextView) view.findViewById(R.id.stockcompany);
        new stock().a = position;
        new stock().execute();
        return view;
    }
    public class stock extends AsyncTask {
        int a;

        @Override
        protected Object doInBackground(Object[] objects) {
            Stock stock = YahooFinance.get(items.get(a));
            tv1.setText(String.valueOf(stock.getName()));
            return null;
        }
    }
}

**Comment by SilverFoxA** [comment]
Ok, so i think i have found the error, for some reason directly accessing the `name` won't work we need to put it in a string and use that string

**Comment by sstrickx** [comment]
Seems a bit strange. Glad you were able to solve your problem.
