### ISSUE TITLE
Downloading from within EU stopped working

### ISSUE THREAD

**Issue by apete** [sstrickx/yahoofinance-api#138]
The html of the EU consent form page changed. This PR fixes the problem:
https://github.com/sstrickx/yahoofinance-api/pull/137

**Comment by oursgamemf** [comment]
thank you very much!

**Comment by oursgamemf** [comment]
> The html of the EU consent form page changed. This PR fixes the problem:
> #137

thank you very much!

**Comment by apete** [comment]
You're welcome. I'm surprised at how "quiet " it is here. I would think a library like this could be useful to many.

I have my own alternative:

https://www.ojalgo.org/2019/04/ojalgo-v47-1-ojalgo-finance-v2-1-financial-time-series-data/

It was while working on that code I discovered this library, used it to compare results and then discovered that it stopped working...

**Comment by oursgamemf** [comment]
yes, I'm surprised too. Nice alternative, I will keep in account. Another way by proprietary API is this one https://www.interactivebrokers.co.uk/it/?f=5041.

**Comment by sstrickx** [comment]
So sorry for the huge delay here. I completely lost track of it. 
Thank you very much for fixing the issue @apete ! 
I'll release a new version with the fix today.

**Comment by sstrickx** [comment]
Fixed and released as version 3.15.0
