### ISSUE TITLE
Ex-dividend date is missing

### ISSUE THREAD

**Issue by ski2day** [sstrickx/yahoofinance-api#139]
The ex-dividend date is missing and is being provided as a single '/'.  This has been reproduced with several ticker symbols.

All other dates are fine.  

This was working and is possibly the result of a change on the Yahoo side.

**Comment by sstrickx** [comment]
Sorry for the late reply @ski2day . This is indeed due to a change at the Yahoo side and we can't really do anything about it. It seems they only provide the dividend pay date now and no longer the ex-dividend date.
