### ISSUE TITLE
Yahoo finance doesn't always use the time zone "America/New_York"

### ISSUE THREAD

**Issue by dreamershl** [sstrickx/yahoofinance-api#14]
SGX, (exchange code: SES)  stock quote data is using the SGT (GMT +8) timezone. For example, the downloaded price for the "D05.SI" Last trade time is as the following. The time is SGT (GMT +8), not the "America/New_York". 

So YahooFinance.TIMEZONE should be configurable for the different market.

![image](https://cloud.githubusercontent.com/assets/1271739/7793714/1c9f6802-02f5-11e5-8403-6afaf305aad0.png)

**Comment by sstrickx** [comment]
Hi, I'm looking into it. 
This won't be easy to solve as it looks like Yahoo Finance doesn't provide the timezone information. I've also read somewhere that the dates would be in the America/New_York timezone while the time would be in the local timezone.
Anyway, I'll try to keep you posted.

**Comment by dreamershl** [comment]
Is it possible to make the "YahooFinance.TIMEZONE" not final. So the application get chance to adjust the timezone accordingly. Or the application is able to set the timezone according to the exchange.

**Comment by sstrickx** [comment]
I'll try to automatically detect the timezone based on the exchange. Sadly, it will not be possible to give a correct time if the exchange is unknown to the library. This should only happen in rare occasions and could be easily fixed with a new version.
Should be ready by next week.

**Comment by sstrickx** [comment]
A small explanation: the correct time zone should now be automatically detected.
In case you still want to manually set the time zone for a specific quote, you can now use the [`StockQuote.getLastTradeDateTime(java.util.TimeZone timeZone)`](http://financequotes-api.com/javadoc/yahoofinance/quotes/stock/StockQuote.html#getLastTradeTime-java.util.TimeZone-) method.

**Comment by dreamershl** [comment]
see your change. Thank for the udpate
