### ISSUE TITLE
Yahoo crumb file is empty when running my app in a shell

### ISSUE THREAD

**Issue by enkara** [sstrickx/yahoofinance-api#140]
I got following error the problem when I run my applichation in a shell like Gitbash or Windows command line. I got following error message:
Error:java.io.IOException: Server returned HTTP response code: 401 for URL: https://query1.finance.yahoo.com/v7/finance/download/AAPL?period1=1522274400&period2=1553814000&interval=1d&crumb=

**BUT - when I run the same application in my IDE (Netbeans/IntelliJ) it just works fine.**
By the way I am accessing from Europe and I am aware that the cause of the problem is accepting the Oath frontPage. 

Does anyone have an idea how to solve it? 

Thanks.

**Comment by sstrickx** [comment]
This was probably the same issue as #138 .
Fixed now and released as version 3.15.0
