### ISSUE TITLE
Upgrade to Java 8

### ISSUE THREAD

**Issue by manoelcampos** [sstrickx/yahoofinance-api#142]
What do you think about upgrading the project source and target versions to Java 8?
Java 8 is an established version, broadly adopted and provides lots of useful features.

**Comment by sfuhrm** [comment]
Opened a PR for that: #150

**Comment by sfuhrm** [comment]
see here for a fork: https://github.com/sfuhrm/yahoofinance-api

**Comment by manoelcampos** [comment]
Thanks for that @sfuhrm.
