### ISSUE TITLE
Detecting failures

### ISSUE THREAD

**Issue by larroy** [sstrickx/yahoofinance-api#15]
I find difficult to distinguish an empty result from a genuine failure, I think when the quote request fail there should be an indication, either an exception or something like a Try object like in Scala....

specifically the part:   

     } catch (IOException ex) {
            YahooFinance.logger.log(Level.SEVERE, ex.toString(), ex);
        }

**Comment by sstrickx** [comment]
You are absolutely right! Will fix this in the next version (should arrive a few days)

**Comment by sstrickx** [comment]
The impact of throwing the IOException is a bit bigger than I expected. It will break the code of everyone who's currently using the library. Therefore I decided to not include it yet in the latest minor release (1.4).
It will definitely be included in release 2.0. I expect to be ready with this somewhere next week.

**Comment by larroy** [comment]
I commited this change in my fork, do you want to have a look to see if that's what you have in mind?

I would prefer something like a Scala / Java8 Try object, but I guess we don't have that luxury if we want to be backwards compatible. 

I want to convert the failures to Try in Scala so I'm using the library with IOException propagated.

**Comment by sstrickx** [comment]
I couldn't really find the changes you made on the fork. (pushed them to Github?)
Anyway, my changes were actually ready for a few days, just finalized the testing. The IOException should now be thrown correctly in release 2.0.0. Please don't hesitate to let me know if you find any other problems like that.

**Comment by larroy** [comment]
Thanks. seems I that accidentally lost the changes. Would you be interested in merging a PR that puts the source in standard maven layout?

├── src
│   └── main
│       └── java
│           └── yahoofinance
│               ├── histquotes
