### ISSUE TITLE
Probably a newbie question, but how do I fix this error...

### ISSUE THREAD

**Issue by alanoatwork** [sstrickx/yahoofinance-api#155]
I'm getting, Missing artifact com.yahoofinance-api:YahooFinanceAPI:jar:3.16.0 in Maven. 

What am I doing wrong?  

Thanks.

**Comment by yuvalevr** [comment]
Hi @alanoatwork,

I noticed you mentioned version 3.16.0 which I wasn't able to find in Maven. I'm getting the following error:
"Could not find artifact com.yahoofinance-api:YahooFinanceAPI:pom:3.16.0 in central (https://repo.maven.apache.org/maven2)"

However, the following steps worked for me:

1) Edit the pom.xml file of your project and add the following dependency:

<dependency>
	<groupId>com.yahoofinance-api</groupId>
	<artifactId>YahooFinanceAPI</artifactId>
	<version>3.15.0</version>
</dependency>

Note that I used version 3.15.0 which is the latest stable release listed here: https://github.com/sstrickx/yahoofinance-api/releases.

2) In Intellij IDEA, right click on the top item in your project's tree -> Maven -> Reimport

Hope this answers your question.
