### ISSUE TITLE
Is it possible to get the image of the token?

### ISSUE THREAD

**Issue by SilverFoxA** [sstrickx/yahoofinance-api#16]
I'm wondering if it's possible to fetch the image of the token with this api.

![checkds](https://cloud.githubusercontent.com/assets/6983070/8155718/8e5ff59a-1364-11e5-832e-2de0b34b8b52.png)

I want to achieve something like this, so we basically get all the above the token symbol, exchange,... except the picture.
So what i want to know is, is it possible to retrieve the company logo with this api?

**Comment by sstrickx** [comment]
I'm sorry, but I'm not sure I understand your question correctly. By token, do you mean the stock symbol? (e.g. "TSLA") And what kind of image would you like to retrieve?

**Comment by SilverFoxA** [comment]
Please check my updated question

**Comment by sstrickx** [comment]
That's much clearer. Sadly, I have to disappoint you. This information is not available from Yahoo Finance.
There is an API from Xignite that seems to provide this functionality, but it looks like you won't be able to get it for free: http://www.xignite.com/product/XigniteLogos

**Comment by SilverFoxA** [comment]
Okay, so can't we perform two request simultaneously? one for the stock and at the same time search for the logo with a http request in google?

**Comment by sstrickx** [comment]
The main problem is that it's out of scope for this library. This data is not available from Yahoo Finance.
Technically, it would be possible to do a Google image search for the company name + logo.
However, I would not recommend this. There are a few drawbacks to take into account:
- Which search result to pick automatically? The first one? That would work most of the time, but won't always be correct.
- Google has a limit on the number of searches you will be able to perform like this. The limit could be high enough for your use case.

The correct way to do this, would be to build up a database for company logos and have an API available to query that database. I'm currently not aware of a free service that provides this functionality.

**Comment by SilverFoxA** [comment]
Well what i was planning is once we know the name of the brand we can get information of the location using google search, from that we can also get the Lat and Lng, which we can use with the `Google Place APi` and google place api provides the image reference url, so we won't have to look for all the searches. well it's a concept though

**Comment by sstrickx** [comment]
That seems a little bit far fetched, but I definitely wish you good luck!
