### ISSUE TITLE
Will a new version be released this year?

### ISSUE THREAD

**Issue by etcos** [sstrickx/yahoofinance-api#169]
Greetings! 
I'm wondering if pull requests will be accepted and a new version will be released?

**Comment by vitalidze** [comment]
Hi

Any update on this? We are waiting for the new version of the library.

Thank you.

**Comment by sfuhrm** [comment]
I've released a source code compatible fork with some cleanups here: https://github.com/sfuhrm/yahoofinance-api

**Comment by danielfc** [comment]
@sfuhrm thanks for putting that together 🍻
