### ISSUE TITLE
Now it seems yahoo doesn't provide the quote downloading anymore 

### ISSUE THREAD

**Issue by dreamershl** [sstrickx/yahoofinance-api#18]
Today I get this following exception. When I manually visit the following URL, yahoo website complains the request format is invalid. 

    java.io.IOException: Server returned HTTP response code: 400 for URL: http://download.finance.yahoo.com/d/quotes.csv?s=D05.SI&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8&e=.csv

**Comment by sstrickx** [comment]
It looks like the provided link is working fine now. Not sure what could've gone wrong.
Could you confirm it's working now?

**Comment by dreamershl** [comment]
No. still get error. Only the history price can work now, which is the following URL

http://ichart.yahoo.com/table.csv?s=D05.SI&a=7&b=11&c=2010&d=7&e=11&f=2015&g=d&ignore=.csv

**Comment by sstrickx** [comment]
Can you check what you get on http://finance.yahoo.com/d/quotes.csv?s=D05.SI&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8&e=.csv ?

Not sure why the URL you provided goes to `download.finance.yahoo.com` instead of `finance.yahoo.com`. Are you using an old / customized version of the API? (the URL you provided still works for me though, so I guess it depends on which of the Yahoo servers our request ends up)
Which IP address do you get for `finance.yahoo.com` ? I'm getting `66.196.66.212`

The result I'm getting:
```
Aug 11, 2015 11:43:14 AM yahoofinance.quotes.QuotesRequest getResult
INFO: Sending request: http://finance.yahoo.com/d/quotes.csv?s=D05.SI&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8&e=.csv
Aug 11, 2015 11:43:15 AM yahoofinance.quotes.QuotesRequest getResult
INFO: Parsing CSV line: \"DBS\",\"D05.SI\",\"SGD\",\"SES\",19.74,N/A,\"D05.SI\",N/A,\"D05.SI\",19.73,N/A,\"D05.SI\",N/A,\"D05.SI\",19.73,\"D05.SI\",3000,\"D05.SI\",\"8/11/2015\",\"5:04pm\",20.16,20.32,19.70,20.25,11408900,3349400,21.50,17.62,20.81,20.41,\"D05.SI\",2478792000,\"D05.SI\",\"D05.SI\",N/A,\"D05.SI\",48.91B,\"D05.SI\",1710565000,\"D05.SI\",N/A,\"7/31/2015\",N/A,N/A,1.62,1.75,0.37,N/A,12.17,1.50,1.29,5.27,15.81,9.56B,0.00,N/A
D05.SI
--------------------------------
symbol: D05.SI
name: DBS
currency: SGD
stockExchange: SES
quote: Ask: 19.74, Bid: 19.73, Price: 19.73, Prev close: 20.32
stats: EPS: 1.62, PE: 12.17, PEG: 1.50
dividend: Pay date: /, Ex date: Fri Jul 31 06:00:00 CEST 2015, Annual yield: 0%
history: null
--------------------------------
```

**Comment by dreamershl** [comment]
I get this. It's redirected



On Tuesday, August 11, 2015, Stijn Strickx <notifications@github.com> wrote:

> Can you check what you get on
> http://finance.yahoo.com/d/quotes.csv?s=D05.SI&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8&e=.csv
> ?
>
> Not sure why the URL you provided goes to download.finance.yahoo.com
> instead of finance.yahoo.com. Are you using an old / customized version
> of the API? (the URL you provided still works for me though, so I guess it
> depends on which of the Yahoo servers our request ends up)
> Which IP address do you get for finance.yahoo.com ? I'm getting
> 66.196.66.212
>
> The result I'm getting:
>
> Aug 11, 2015 11:43:14 AM yahoofinance.quotes.QuotesRequest getResult
> INFO: Sending request: http://finance.yahoo.com/d/quotes.csv?s=D05.SI&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8&e=.csv
> Aug 11, 2015 11:43:15 AM yahoofinance.quotes.QuotesRequest getResult
> INFO: Parsing CSV line: \"DBS\",\"D05.SI\",\"SGD\",\"SES\",19.74,N/A,\"D05.SI\",N/A,\"D05.SI\",19.73,N/A,\"D05.SI\",N/A,\"D05.SI\",19.73,\"D05.SI\",3000,\"D05.SI\",\"8/11/2015\",\"5:04pm\",20.16,20.32,19.70,20.25,11408900,3349400,21.50,17.62,20.81,20.41,\"D05.SI\",2478792000,\"D05.SI\",\"D05.SI\",N/A,\"D05.SI\",48.91B,\"D05.SI\",1710565000,\"D05.SI\",N/A,\"7/31/2015\",N/A,N/A,1.62,1.75,0.37,N/A,12.17,1.50,1.29,5.27,15.81,9.56B,0.00,N/AD05.SI
> --------------------------------
> symbol: D05.SI
> name: DBS
> currency: SGD
> stockExchange: SES
> quote: Ask: 19.74, Bid: 19.73, Price: 19.73, Prev close: 20.32
> stats: EPS: 1.62, PE: 12.17, PEG: 1.50
> dividend: Pay date: /, Ex date: Fri Jul 31 06:00:00 CEST 2015, Annual yield: 0%
> history: null
> --------------------------------
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sstrickx/yahoofinance-api/issues/18#issuecomment-129793713>
> .
>


-- 
Sent from Gmail Mobile

**Comment by dreamershl** [comment]
Btw, I am from Singapore. Will try to find out the IP address once I am
back to office

On Tuesday, August 11, 2015, Shen Liang <shenliang@dt-workshop.com> wrote:

>
>
> On Tuesday, August 11, 2015, Shen Liang <shenliang@dt-workshop.com
> <javascript:_e(%7B%7D,'cvml','shenliang@dt-workshop.com');>> wrote:
>
>> I get this. It's redirected
>>
>>
>>
>> On Tuesday, August 11, 2015, Stijn Strickx <notifications@github.com>
>> wrote:
>>
>>> Can you check what you get on
>>> http://finance.yahoo.com/d/quotes.csv?s=D05.SI&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8&e=.csv
>>> ?
>>>
>>> Not sure why the URL you provided goes to download.finance.yahoo.com
>>> instead of finance.yahoo.com. Are you using an old / customized version
>>> of the API? (the URL you provided still works for me though, so I guess it
>>> depends on which of the Yahoo servers our request ends up)
>>> Which IP address do you get for finance.yahoo.com ? I'm getting
>>> 66.196.66.212
>>>
>>> The result I'm getting:
>>>
>>> Aug 11, 2015 11:43:14 AM yahoofinance.quotes.QuotesRequest getResult
>>> INFO: Sending request: http://finance.yahoo.com/d/quotes.csv?s=D05.SI&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8&e=.csv
>>> Aug 11, 2015 11:43:15 AM yahoofinance.quotes.QuotesRequest getResult
>>> INFO: Parsing CSV line: \"DBS\",\"D05.SI\",\"SGD\",\"SES\",19.74,N/A,\"D05.SI\",N/A,\"D05.SI\",19.73,N/A,\"D05.SI\",N/A,\"D05.SI\",19.73,\"D05.SI\",3000,\"D05.SI\",\"8/11/2015\",\"5:04pm\",20.16,20.32,19.70,20.25,11408900,3349400,21.50,17.62,20.81,20.41,\"D05.SI\",2478792000,\"D05.SI\",\"D05.SI\",N/A,\"D05.SI\",48.91B,\"D05.SI\",1710565000,\"D05.SI\",N/A,\"7/31/2015\",N/A,N/A,1.62,1.75,0.37,N/A,12.17,1.50,1.29,5.27,15.81,9.56B,0.00,N/AD05.SI
>>> --------------------------------
>>> symbol: D05.SI
>>> name: DBS
>>> currency: SGD
>>> stockExchange: SES
>>> quote: Ask: 19.74, Bid: 19.73, Price: 19.73, Prev close: 20.32
>>> stats: EPS: 1.62, PE: 12.17, PEG: 1.50
>>> dividend: Pay date: /, Ex date: Fri Jul 31 06:00:00 CEST 2015, Annual yield: 0%
>>> history: null
>>> --------------------------------
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/sstrickx/yahoofinance-api/issues/18#issuecomment-129793713>
>>> .
>>>
>>
>>
>> --
>> Sent from Gmail Mobile
>>
>
>
> --
> Sent from Gmail Mobile
>


-- 
Sent from Gmail Mobile

**Comment by dreamershl** [comment]
This is the ping result. Pls have a look.

ping finance.yahoo.com
PING fd-geoycpi-uno-deluxe.gycpi.b.yahoodns.net (106.10.199.10): 56 data bytes
64 bytes from 106.10.199.10: icmp_seq=0 ttl=54 time=4.368 ms
64 bytes from 106.10.199.10: icmp_seq=1 ttl=54 time=4.334 ms
64 bytes from 106.10.199.10: icmp_seq=2 ttl=54 time=4.158 ms
64 bytes from 106.10.199.10: icmp_seq=3 ttl=54 time=4.155 ms

**Comment by sstrickx** [comment]
I get that 106.10.199.10 is currently unavailable... 
Probably, finance.yahoo.com should no longer resolve to this IP, but your DNS might have cached this value. Could you give it a try with Google's Public DNS? ( https://developers.google.com/speed/public-dns/?hl=en )
![screen shot 2015-08-12 at 08 25 45](https://cloud.githubusercontent.com/assets/5104204/9217724/73908380-40cb-11e5-9f20-36a04c6c683c.png)

**Comment by dreamershl** [comment]
I am using 8.8.8.8. This is what I get from the DNS query. And from the error message, it is not like the server down. 

dig finance.yahoo.com

; <<>> DiG 9.8.3-P1 <<>> finance.yahoo.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60488
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;finance.yahoo.com.		IN	A

;; ANSWER SECTION:
finance.yahoo.com.	143	IN	CNAME	fd-geoycpi-uno-deluxe.gycpi.b.yahoodns.net.
fd-geoycpi-uno-deluxe.gycpi.b.yahoodns.net. 35 IN A 106.10.199.11
fd-geoycpi-uno-deluxe.gycpi.b.yahoodns.net. 35 IN A 106.10.199.10

;; Query time: 31 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Aug 12 19:34:11 2015
;; MSG SIZE  rcvd: 123

**Comment by dreamershl** [comment]
:) sorry, after retry the URL, now it is OK. I get the result correctly. Looks like, Yahoo server get some problem. Thanks. Lucky, they still provide the service to the public.

**Comment by sstrickx** [comment]
Seems like it was indeed an issue on Yahoo's side... Strange that it took them so long to resolve that.
Glad it's working again for you! Please don't hesitate to create a new issue if you encounter any other problems.
