### ISSUE TITLE
Null values from StockStats

### ISSUE THREAD

**Issue by Dr-Corn-Inspector** [sstrickx/yahoofinance-api#186]
Getting Revenue, PEG, and EBITDA will return null, regardless of the stock.

Example:

Stock stock = YahooFinance.get("INTC");
		
System.out.println(stock.getStats().getRevenue());

will return null

**Comment by eztam-** [comment]
The used endpoint from Yahoo  Finance ([https://query1.finance.yahoo.com/v7/finance/quote?symbols=INTC](https://query1.finance.yahoo.com/v7/finance/quote?symbols=INTC)) simply doesn't return the revenue. So it's not possible to get it. The code for this was also commented in `StockQuotesQuery1V7Request#getStats(JsonNode)`.
