### ISSUE TITLE
Not sure

### ISSUE THREAD

**Issue by amandoee** [sstrickx/yahoofinance-api#187]
YahooFinance.get("");

"get" is underlined in red, and says "Unhandled exception: java.io.IOException"

**Comment by AdampBoucher** [comment]
Late writing, just got it to work for me, you want to import the java.io.IOException library. This is everything I imported to get it to work:
`import yahoofinance.Stock; 
import yahoofinance.YahooFinance; 
import java.io.IOException; 
import java.math.BigDecimal;`
