### ISSUE TITLE
Time-outs

### ISSUE THREAD

**Issue by peternees** [sstrickx/yahoofinance-api#191]
Hi, I get time-outs. Is the Yahoo service (/v7) still working? it is in yhStock.getHistory()

**Comment by killerlegs** [comment]
Yupp, as of today. It was still working yesterday.

It seems the crumbs (cookie) code is doing a regex match which doesn't return for the given line.

This can happen, when the regex expression is too complex (catastrophic backtracking) but I haven't looked into it any further.

**Comment by jcz5163** [comment]
I am also getting time-outs, can confirm this was working yesterday as well.

**Comment by gbgdeveng** [comment]
same here
v8 request runs fine, however

**Comment by jgoss1074** [comment]
How do you make v8 requests?

**Comment by killerlegs** [comment]
This fixes it for me, but I'm not 100% sure it's still doing the same thing. I'm never running into the postFind if-clause, so couldn't test patternInput. But other than that, it seems to work fine again after the changes.

I don't see why you'd need a "(.*)" here at the beginning or end. The group is not even used.

![crumbsmanager](https://user-images.githubusercontent.com/32152103/165968663-3d32fa5a-dfa3-4558-9bf7-11a28edea948.png)

**Comment by gbgdeveng** [comment]
Thanks @killerlegs, this worked for me

**Comment by gbgdeveng** [comment]
Thanks @killerlegs, this worked for me!

**Comment by peternees** [comment]
Great! Is it possible to push a new version with this patch?

**Comment by killerlegs** [comment]
@peternees Are you in the US? If not, try using a proxy.

I know that yahoo redirects to different pages depending on the country, you live in.

**Comment by peternees** [comment]
Thanks for the suggestion. I am on Google Appengine, so that is US yes. I will try that.

**Comment by peternees** [comment]
Fixed, the problem was my side. The change of the pattern as suggested by @killerlegs is the only required.

**Comment by killerlegs** [comment]
@peternees Glad you got it to work!

**Comment by sstrickx** [comment]
Hi all,

Sorry, only just noticed this. I'll do my best to release a fix soon.

**Comment by sstrickx** [comment]
Fixed in new version: 3.16.0
