### ISSUE TITLE
symbol search

### ISSUE THREAD

**Issue by maku** [sstrickx/yahoofinance-api#21]
it would be great to be able to search a symbol by name (e.g.  http://d.yimg.com/autoc.finance.yahoo.com/autoc?query=yahoo&callback=YAHOO.Finance.SymbolSuggest.ssCallback)

Is this already possible?

**Comment by sstrickx** [comment]
Currently this is not possible.
I'm not really convinced it should be included in this library either. 

It looks like that service is very much for Yahoo's internal use only. They probably execute the result directly as Javascript on their website to display some symbol search results.
While it would be pretty easy to strip the data and parse it as JSON, it just doesn't feel right.
