### ISSUE TITLE
Is it possible to query yahoo for more information?

### ISSUE THREAD

**Issue by charbelgereige** [sstrickx/yahoofinance-api#22]
I am trying to write a sort of stock scanner, that would collect prices and economic data and statistics about a huge universe of stocks. I'm using your YahooFinance-API for this.

The additional things that I would like to be able to get are statistics about the debt and cashflows, and cash. 
Is it possible to retrieve this?

Also, I would like to be able to get the sector classification, so that I can compare some of this data to the sector average.

**Comment by sstrickx** [comment]
Sadly, the Yahoo Finance API doesn't seem to provide any information about the cashflow.
No information about the sector classification available either.

We'd need to get this information from a different service.
Sorry I couldn't be of more help.
