### ISSUE TITLE
Can you tell me the delay time for the stock?

### ISSUE THREAD

**Issue by marcochin** [sstrickx/yahoofinance-api#23]
@sstrickx Hey, I've noticed that the stock prices have a certain delay time and from my testing it is about 30 minute delay. I don't really mind that much, but do you know the exact delay time? Thanks!

**Comment by sstrickx** [comment]
Hey marcochin. They delay time depends on the exchange. Yahoo Finance provides a clear overview for the different exchanges: http://finance.yahoo.com/exchanges

The [StockQuote](http://financequotes-api.com/javadoc/yahoofinance/quotes/stock/StockQuote.html) object also has the [getLastTradeTime()](http://financequotes-api.com/javadoc/yahoofinance/quotes/stock/StockQuote.html#getLastTradeTime--) method available. This should give you an indication of when the quote was relevant. (I guess you were already aware of this)
