### ISSUE TITLE
Yahoo Finance historical quote limits?

### ISSUE THREAD

**Issue by marcochin** [sstrickx/yahoofinance-api#26]
@sstrickx Hey, I've noticed that historical quotes make separate calls to ichart.yahoo.com. If I need historical data for 100 stocks, it would require 100 calls to yahoo. I'm worried this will be too much for yahoo servers to handle. Do you know the limits of this?

**Comment by sstrickx** [comment]
Hi, very good question!
Yahoo never made a clear statement about this and I never tried to test the limit. It looks like they have a public limit on YQL of about 2,000 requests/hour per IP. I guess it will not be too different for the historical quotes.
Not sure how often you'd like to fetch the historical data for these +- 100 stocks. If you just need it a few times per day, I guess you shouldn't worry too much about it.
