### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by akkatracker** [sstrickx/yahoofinance-api#27]
I know this isn't a StackOverflow but I felt it might be a bit more helpful to ask the library dev. 

I'm writing a quick stock app to help me learn Android. I have a basic understanding of Java and a moderate understanding of Android. 

This method is being unable to be fully run and is exiting with an IllegalStateException - pointing to the Stock stock = YahooFinance.get(stockcodetext) line. I have properly imported the library and the app is actually calling the API properly but crashing very soon afterwards. 

I suspect the issue is arising for some elementary misunderstanding but on the offchance that its an issue with your library I have posted it here.

Could you help (thanks by the way for the library, saves myself many lines of clunky code)? If not feel free to close the issue. 

Thanks 

'''
public void getStockPrice(View v) throws IOException {
        EditText stockcode = (EditText) findViewById(R.id.user_entered_code); //This is what the user enters
        TextView finalstock = (TextView) findViewById(R.id.stockcode); //This is the big stock code displayed
        TextView stockprice = (TextView) findViewById(R.id.price);
        String stockcodetext = stockcode.getText().toString();
        Log.d("s", stockcodetext);

        Stock stock = YahooFinance.get(stockcodetext);
        BigDecimal price = stock.getQuote(true).getPrice();;

        stockprice.setText(String.valueOf(price));
        finalstock.setText(stockcode.toString());

    }
'''

**Comment by akkatracker** [comment]
Found the issue: http://stackoverflow.com/questions/6343166/android-os-networkonmainthreadexception

**Comment by sstrickx** [comment]
Glad you found the solution for your problem! Please don't hesitate to open another issue here on Github in case you encounter any further issues with the library.

**Comment by akkatracker** [comment]
Thanks mate, appreciate it - got my first rendition of the app working - Library works perfectly.
