### ISSUE TITLE
Missing Zurich time zone 

### ISSUE THREAD

**Issue by sdecoppet** [sstrickx/yahoofinance-api#28]
I get a warning when loading the Euro Stoxx 50 TR (SX5T.Z)  yahoofinance.exchanges.ExchangeTimeZone.get Cannot find time zone for exchange suffix: 'Z'. Using default: America/New_York

It outputs a wrong lastTradeTime in the quote, like 16h30 instead of 10h30.

**Comment by sstrickx** [comment]
As a temporary workaround, you could use the ```StockQuote``` its ```getLastTradeTime(java.util.TimeZone timeZone)``` method for this item. (http://financequotes-api.com/javadoc/yahoofinance/quotes/stock/StockQuote.html#getLastTradeTime-java.util.TimeZone-)
This method will use the provided time zone to parse the time.

I'll create a fix this weekend by adding Zurich.

**Comment by sdecoppet** [comment]
Thanks a lot for the fix! ...and for the lib, very useful.
