### ISSUE TITLE
Dividends always seems to be 0 

### ISSUE THREAD

**Issue by thysmichels** [sstrickx/yahoofinance-api#34]
I am looking for dividend information but annualYield and  annualYieldPercent always seem to return 0.

Example:
```
"dividend": {
    "symbol": "BNDX",
    "annualYield": 0,
    "annualYieldPercent": 0
  }
```

**Comment by sstrickx** [comment]
This means that the dividend data is not available from Yahoo Finance for that stock.
If you try for example with "INTC", you'll see that the library is working correctly.
There's nothing I can do about this, sorry!
