### ISSUE TITLE
getInt failed to parse a big integer

### ISSUE THREAD

**Issue by peternees** [sstrickx/yahoofinance-api#38]
yahoofinance.Utils getInt: Failed to parse: 3268646600

**Comment by sstrickx** [comment]
I'll have a look at it. Can you provide the stock symbol for which this error occurred? (would like to see which field is causing the problem)

**Comment by peternees** [comment]
hi Stijn,

an example is PG.MI.

gives two different warning::
- yahoofinance.Utils getInt: Failed to parse: 11606104800
- yahoofinance.Utils getInt: Failed to parse: 6056731200

You are Dutch?

best regards
Peter

2016-02-29 23:03 GMT+01:00 Stijn Strickx <notifications@github.com>:

> I'll have a look at it. Can you provide the stock symbol for which this
> error occurred? (would like to see which field is causing the problem)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sstrickx/yahoofinance-api/issues/38#issuecomment-190417543>
> .
>



-- 
*Uncle Stock*

www.unclestock.com
follow on twitter: @UncleStock
follow on facebook: www.facebook.com/unclestock

**Comment by sstrickx** [comment]
Thanks for the info, I did not immediately imagine the bid size and ask size exceeding 2 billion, but it makes sense for such a low price.
I'll change the type to long instead of int. (new version will be 3.x.x since it breaks compatibility)

Yea, from BE, just like you.

**Comment by peternees** [comment]
Ok bedankt!
Op 1-mrt.-2016 18:57 schreef "Stijn Strickx" <notifications@github.com>:
