### ISSUE TITLE
Move from Maven to Gradle

### ISSUE THREAD

**Issue by jaredsburrows** [sstrickx/yahoofinance-api#46]
- Publish jars
- Publish javadocs

**Comment by sstrickx** [comment]
Hi Jared,

I see no reason to move from maven to gradle.
All jars and javadocs are already being published to maven central as well.
Anything specific I'm missing here?

**Comment by jaredsburrows** [comment]
@sstrickx Nah, I just wanted ask before I tried sending in a pull request.

**Comment by sstrickx** [comment]
Alright, thanks for checking! I still prefer Maven over Gradle for most of my projects. (depends a bit on the project)

**Comment by jaredsburrows** [comment]
@sstrickx Sounds good. Thanks for the fast reply.
