### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by jaredsburrows** [sstrickx/yahoofinance-api#47]
Add TravisCI

**Comment by jaredsburrows** [comment]
@sstrickx If you turn on TravisCI, I can make a PR for the README.

**Comment by sstrickx** [comment]
Thanks, that would be great. I've activated TravisCI.
https://travis-ci.org/sstrickx/yahoofinance-api

There's some work I still need to do to allow for good tests, but it's something I'll work on when I'm back from holidays. (#48)
