### ISSUE TITLE
Improve code to facilitate better testing

### ISSUE THREAD

**Issue by sstrickx** [sstrickx/yahoofinance-api#48]
Provide an interface to allow mocking of the http request. 
Otherwise the tests would depend on an external service and everyone running the tests would be constantly sending a bunch of requests to Yahoo Finance. Let's try to avoid that.
By mocking the HTTP request we can also provide a reproducible test environment.

**Comment by jaredsburrows** [comment]
You can use: https://github.com/square/okhttp/tree/master/mockwebserver.

**Comment by lokkersp** [comment]
Hey, you do a nice thing with this project, thank you. What do you thinking about add tests?

**Comment by sstrickx** [comment]
Hi, I'm currently working on writing the tests using the mockwebserver suggested by @jaredsburrows. It's going really well, so I should be able to push the changes sometime this week.

**Comment by lokkersp** [comment]
Can I help you with it? Sometimes I write tests with [Spock](https://github.com/spockframework/spock), and it's great. It helps write very very readable tests. Best regards.

**Comment by sstrickx** [comment]
Tests are now very easy to implement with the mocked web server. A simple requests.yml file can be updated to provide new mock responses to specific requests.

**Comment by jaredsburrows** [comment]
@sstrickx I am just now seeing this. Sorry for the late response. Were you able to get it setup? Did you need help?
