### ISSUE TITLE
Stocks always delayed 15 minutes

### ISSUE THREAD

**Issue by FrostRocket** [sstrickx/yahoofinance-api#60]
What's the deal with the 15 minute delays on quotes? Is this a limitation of the API or is there a configuration I'm missing to get real-time data?

**Comment by derrix060** [comment]
It deppends of your Exchange. You can see the full list here: http://finance.yahoo.com/exchanges?bypass=true

**Comment by FrostRocket** [comment]
Thanks for the clarification!
