### ISSUE TITLE
Bitcoin?

### ISSUE THREAD

**Issue by EXJUSTICE** [sstrickx/yahoofinance-api#65]
So while one can get Live bitcoin data using the id = "BTCUSD=X", we cannot fetch any HistoricalQuotes. Ggetting a NullPointerException when trying to reverse the list of HistoricalQuotes.
However, looking into the Yahoo Finance page displays the data with no issues.

Does this boil down from a requirement for a getClose() value - if no getClose() can be calculated, we dont get an object? Would it be possible to approximate this with (getHigh()+getLow())/2 ?

**Comment by wlynnInhanceTechnology** [comment]
instead of approximating the data and providing wrong information to users. Which would be a disaster for financials.
Simple have a isClose() boolean

**Comment by EXJUSTICE** [comment]
So the API would refuse to provide a value if there is no Close value, right?

**Comment by wlynnInhanceTechnology** [comment]
I think in your scenario, you are trying to get the intraday or EOD values, before they are available by the underlying system. 
This core java library is not the best for getting intraday data, it only gets EOD data about 5 hours after close.
For BTC intra day data use something like 
http://chartapi.finance.yahoo.com/instrument/1.0/NFLX/chartdata;type=quote;range=1d/csv
where NFLX is the symbol you are looking for.
The data this returns it the O,C,H,L,V minute by minute in 60 second intervals.

**Comment by sstrickx** [comment]
I don't think FX is supported at all by the Yahoo ichart API (used to retrieve historical quotes).
Currently looking into some of Yahoo's other APIs which might in fact be able to provide the data you're looking for (#67).

**Comment by derrix060** [comment]
maybe you can use this: https://developer.yahoo.com/yql/console/?q=https%3A%2F%2Fraw.githubusercontent.com%2Fyql%2Fyql-tables%2Fmaster%2Fyahoo%2Ffinance%2Fyahoo.finance.quotes.xml%22%20as%20quotes%3B%0Aselect%20*%20from%20quotes%20where%20symbol%20in%20(%22CIEL3.SA%22)&env=store://datatables.org/alltableswithkeys#h=select+*+from+yahoo.finance.xchange+where+pair+in+(%22BTCUSD%22)
