### ISSUE TITLE
Stock.getHistory stopped working from April 17

### ISSUE THREAD

**Issue by kejuntong** [sstrickx/yahoofinance-api#69]
it looks Stock.getHistory stopped working now. The getResult() method in HistQuotesRequest class will always give an empty list since the br.readLine() is always giving null now.

**Comment by aghajani** [comment]
it's because yahoo tries to redirect you to https, and so return a 301 (Moved Permanently) response. and in HttpURLConnection they didn't set redirection follow enabled! If I have enough time, I will try to fix and send a PR!

**Comment by aghajani** [comment]
P.S. as a workaround you can put this line in very start of your app (MainActivity oncreate or ApplicationStart, ...):
        System.setProperty("yahoofinance.baseurl.histquotes", "https://ichart.yahoo.com/table.csv");
it will cause this lib to use https directly ;)

**Comment by alketola** [comment]
Thanks @aghajani , from me and I suppose from other fellow students of Android Developer Fast Track /Nanodegree students studying Udacity.com, Confirmed, it works!

**Comment by hrvester** [comment]
Thank you @aghajani ! The workaround works for me too.

**Comment by sstrickx** [comment]
Thanks for the workaround @aghajani. I'll release a fixed version this evening.

**Comment by aghajani** [comment]
@alketola  I'm on the course too ;) 
Happy to be helpful 👍

**Comment by kejuntong** [comment]
@aghajani Thank you so much for the quick response! The workaround works for me as well!

**Comment by vrendina** [comment]
Requesting bulk stock quotes still works, but if you look at `curl -v "http://finance.yahoo.com/d/quotes.csv"` it also throws an HTTP 301 with the response: 

> Description: The document you requested has moved to a new location.  The new location is "http://download.finance.yahoo.com/d/quotes.csv".

Might want to update the `QUOTES_BASE_URL` to reflect that change. I guess it still works because it isn't redirecting to https?

**Comment by sstrickx** [comment]
@vrendina The redirect is automatically followed as long as the protocol doesn't change. That's the reason why the quotes still work but the historical quotes are failing (protocol redirect from http -> https).
I'm currently implementing a solution to also follow a protocol redirect.
The default URLs will also be updated as you suggested (eliminating some redirects should make it slightly faster / more efficient).

**Comment by blackguardian89** [comment]
You just have to always check the versions of the gradle libraries you use. The current issue is easily solved when you change the version of the Yahoo Finance Library from 3.5.0 to 3.6.1:
https://mvnrepository.com/artifact/com.yahoofinance-api/YahooFinanceAPI

**Comment by Harrymon12** [comment]
Yahoo finance API is not available anymore. I have moved to MarketXLS after this change, much more reliable data.

**Comment by 127bit** [comment]
There is a description of an alternative in this video: https://www.youtube.com/watch?v=Glm9NYJ26iQ
