### ISSUE TITLE
Get Hourly Data

### ISSUE THREAD

**Issue by jtv7** [sstrickx/yahoofinance-api#72]
Is there any way to get hourly data with this API, like throughout the trading day?

**Comment by sstrickx** [comment]
The current API that we're targeting on the side of Yahoo Finance doesn't support this.
I've been looking into supporting / using some of the other APIs that are available (#67), but not sure yet whether this is allowed by Yahoo. Anyway that would take some time to be implemented as I'm currently focused on other projects.
