### ISSUE TITLE
No debug/parse logging by default

### ISSUE THREAD

**Issue by sergiocormio** [sstrickx/yahoofinance-api#73]
Make logging easily configurable.
I'm getting 6 lines of log by STDOUT or STDERR every time I request a quote.
It would be very useful to be able to turn-off this kind of log. (I'm using log4j in my project)

My example log:
may 02, 2017 5:31:47 PM yahoofinance.quotes.QuotesRequest getResult
INFORMACIÓN: Sending request: http://finance.yahoo.com/d/quotes.csv?s=TSLA&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s7&e=.csv
may 02, 2017 5:31:48 PM yahoofinance.quotes.QuotesRequest getResult
INFORMACIÓN: Parsing CSV line: \"Tesla, Inc. \",\"TSLA\",\"USD\",\"NMS\",318.00,N/A,\"TSLA\",100,\"TSLA\",317.75,N/A,\"TSLA\",100,\"TSLA\",318.89,\"TSLA\",67530,\"TSLA\",\"5/2/2017\",\"4:00pm\",324.07,322.83,316.56,327.66,2378047,5711080,327.66,178.19,287.53,238.48,\"TSLA\",161670000,\"TSLA\",\"TSLA\",N/A,\"TSLA\",51.55B,\"TSLA\",119328000,\"TSLA\",N/A,N/A,N/A,N/A,-4.68,-2.40,-0.70,1.79,N/A,-3.84,10.97,7.46,29.42,7.00B,319.92M,262.82,5.27
may 02, 2017 5:31:48 PM yahoofinance.histquotes.HistQuotesRequest getResult
INFORMACIÓN: Sending request: http://ichart.yahoo.com/table.csv?s=TSLA&a=4&b=2&c=2016&d=4&e=2&f=2017&g=m&ignore=.csv

Thanks!

**Comment by sstrickx** [comment]
Hi,

The logging is done with JUL. (probably should've used SLF4J instead...)

You can use the Log4j JUL adapter to configure the log level to `WARN` if you don't want it to be so verbose: https://logging.apache.org/log4j/2.0/log4j-jul/

Alternatively, you could create a separate configuration for JUL to adjust the log level.
Create a file `logging.properties` and let the JUL know where to find it by setting the following property:
`-Djava.util.logging.config.file="logging.properties" `
Content of the file should look like this:
```
# Global logging level. 
.level= INFO
# Package specific logging level
yahoofinance.level = WARNING
```
