### ISSUE TITLE
getHistory returns http 502 response

### ISSUE THREAD

**Issue by hrvestor** [sstrickx/yahoofinance-api#74]
I get the below exception for getHistory now. I use v3.6.1 jar and it was working fine this morning.

java.io.IOException: Server returned HTTP response code: 502 for URL: https://ichart.yahoo.com/table.csv?s=amat&a=4&b=16&c=2016&d=4&e=16&f=2017&g=d&ignore=.csv

Thanks.

**Comment by sstrickx** [comment]
Hi,

It looks like the Yahoo API is down at the moment.
This is not an issue we can help with. We can only wait until they fix the problem.

**Comment by hrvestor** [comment]
Thank you for your prompt response! I'll keep checking for the API status.
