### ISSUE TITLE
Stock splits

### ISSUE THREAD

**Issue by peternees** [sstrickx/yahoofinance-api#78]
I'm wondering whether the API gets stock split information.
It used to be accessable via 
`http://ichart.finance.yahoo.com/x?s=AAPL&a=00&b=2&c=2000&g=v&ignore=.csv`
(which is also not working anymore)

**Comment by sstrickx** [comment]
Currently this Java API doesn't support that functionality.
It does look like the Query1 API has the same information available:
https://query1.finance.yahoo.com/v7/finance/download/GOOG?period1=1325376000&period2=1495792800&interval=1mo&events=split&crumb=mycrumb

Notice the `events=split`.
That gives a result like this:
```
Date,Stock Splits
2014-03-27,2002/1000
2015-04-27,10000000/10000000
```

This could be added as a new feature to version 4.0.0.
