### ISSUE TITLE
^DJI

### ISSUE THREAD

**Issue by peternees** [sstrickx/yahoofinance-api#86]
I fail to get any data for the Dow Jones index, symbol ^DJI. (this means the price is empty)
Any experience whether I should pass the symbol differently? encoding the special character with %5E, does not seem to help. Any ideas?

**Comment by sstrickx** [comment]
Hi, sorry for coming back to you so late. Yahoo doesn't distribute the data for DJI anymore: https://github.com/sstrickx/yahoofinance-api/issues/61

**Comment by sstrickx** [comment]
Seems to be working now as well since #105.
