### ISSUE TITLE
Additional return types

### ISSUE THREAD

**Issue by benmccann** [sstrickx/yahoofinance-api#88]
`HistoricalQuote` isn't a class that's very useful to me. I would need to convert it to some other type to do anything with it. I would much rather have access to the underlying CSV since that's a more common format.

[quandl4j](http://quandl4j.org/) is a similar project for fetching financial data from [quandl](https://www.quandl.com/). They're currently working on making the API client generic such that it can return varying types https://github.com/jimmoores/quandl4j/issues/31. Do you think a similar approach would make sense here so that we return `HistoricalQuote`, the CSV as a `String`, a [Tablesaw](https://jtablesaw.wordpress.com/) `Table`, etc.?

**Comment by sstrickx** [comment]
I'm sorry, but I don't think that should be part of this project. There's one model that's used to represent the data. If you'd like a different representation, it's best to write some converters where necessary.

**Comment by benmccann** [comment]
I somewhat understand this and thank you for the response. The thing is though that the data is originally in CSV format and it seems silly to convert from CSV to `HistoricalQuote` and then back to CSV again. Is there another solution we could consider for returning the underlying data? I would have to think there's some reasonably clean solution for this.

**Comment by sstrickx** [comment]
I understand that it might seem a bit silly, but I wouldn't worry too much about that as long as it keeps your code clean. The performance impact is minimal.
It could be possible to store the CSV line into the `HistoricalQuote` object such that the original raw data can be retrieved using a new method `HistoricalQuote.getRawData()`. Still not a big fan of that though.
