### ISSUE TITLE
Unable to parse date

### ISSUE THREAD

**Issue by squeirozmello** [sstrickx/yahoofinance-api#9]
Hi,

I am using your code:

Stock stock = YahooFinance.get("INTC");
BigDecimal price = stock.getQuote(true).getPrice();

And I have this erros, I think this probably is in your end..

Thanks!!

Mar 04, 2015 5:58:25 PM yahoofinance.quotes.QuotesRequest getResult
     [java] INFO: Sending request: http://finance.yahoo.com/d/quotes.csv?s=INTC&f=n0sc4x0a0b2sa5sb0b3sb6sl1sk3sd1t1o0p0g0h0v0a2k0j0m3m4sj2sss1sj1sf6sr1q0d0y0e0e7e9e8r0r5p6p5b4s6j4t8&e=.csv
     [java] Mar 04, 2015 5:58:25 PM yahoofinance.quotes.QuotesRequest getResult
     [java] INFO: Parsing CSV line: \"Intel Corporation\",\"INTC\",\"USD\",\"NasdaqNM\",34.23,34.23,\"INTC\",11,300,\"INTC\",34.22,34.22,\"INTC\",6,200,\"INTC\",34.23,\"INTC\",100,\"INTC\",\"3/4/2015\",\"11:43am\",33.86,34.095,33.72,34.24,9239085,28483100,37.90,24.38,34.5329,34.7955,\"INTC\",  4,736,000,000,\"INTC\",\"INTC\",-,\"INTC\",162.1B,\"INTC\",  4,729,180,000,\"INTC\",\"Mar  1\",\"Feb  4\",0.915,2.68,2.31,2.38,0.55,2.60,14.76,1.59,2.90,2.89,11.766,55.870B,24.191B,37.27
     [java] Mar 04, 2015 5:58:25 PM yahoofinance.Utils parseDividendDate
     [java] SEVERE: Unparseable date: "Feb  4"
     [java] java.text.ParseException: Unparseable date: "Feb  4"
     [java] 	at java.text.DateFormat.parse(DateFormat.java:357)
     [java] 	at yahoofinance.Utils.parseDividendDate(Utils.java:176)
     [java] 	at yahoofinance.quotes.stock.StockQuotesData.getDividend(StockQuotesData.java:88)
     [java] 	at yahoofinance.quotes.stock.StockQuotesData.getStock(StockQuotesData.java:105)
     [java] 	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:336)
     [java] 	at yahoofinance.YahooFinance.get(YahooFinance.java:76)
     [java] 	at yahoofinance.YahooFinance.get(YahooFinance.java:61)
     [java] 	at it.sqm.stockmarkets.StockMarkets.main(StockMarkets.java:20)
     [java] Mar 04, 2015 5:58:25 PM yahoofinance.quotes.QuotesRequest getResult
     [java] INFO: Sending request: http://finance.yahoo.com/d/quotes.csv?s=INTC&f=n0sc4x0a0b2sa5sb0b3sb6sl1sk3sd1t1o0p0g0h0v0a2k0j0m3m4sj2sss1sj1sf6sr1q0d0y0e0e7e9e8r0r5p6p5b4s6j4t8&e=.csv
     [java] Mar 04, 2015 5:58:26 PM yahoofinance.quotes.QuotesRequest getResult
     [java] INFO: Parsing CSV line: \"Intel Corporation\",\"INTC\",\"USD\",\"NasdaqNM\",34.23,34.23,\"INTC\",11,300,\"INTC\",34.22,34.22,\"INTC\",6,200,\"INTC\",34.23,\"INTC\",100,\"INTC\",\"3/4/2015\",\"11:43am\",33.86,34.095,33.72,34.24,9239085,28483100,37.90,24.38,34.5329,34.7955,\"INTC\",  4,736,000,000,\"INTC\",\"INTC\",-,\"INTC\",162.1B,\"INTC\",  4,729,180,000,\"INTC\",\"Mar  1\",\"Feb  4\",0.915,2.68,2.31,2.38,0.55,2.60,14.76,1.59,2.90,2.89,11.766,55.870B,24.191B,37.27
     [java] Mar 04, 2015 5:58:26 PM yahoofinance.Utils parseDividendDate
     [java] SEVERE: Unparseable date: "Feb  4"
     [java] java.text.ParseException: Unparseable date: "Feb  4"
     [java] 	at java.text.DateFormat.parse(DateFormat.java:357)
     [java] 	at yahoofinance.Utils.parseDividendDate(Utils.java:176)
     [java] 	at yahoofinance.quotes.stock.StockQuotesData.getDividend(StockQuotesData.java:88)
     [java] 	at yahoofinance.Stock.update(Stock.java:44)
     [java] 	at yahoofinance.Stock.getQuote(Stock.java:84)
     [java] 	at it.sqm.stockmarkets.StockMarkets.main(StockMarkets.java:21)
     [java] Mar 04, 2015 5:58:26 PM yahoofinance.Stock update
     [java] INFO: Updated Stock with symbol: INTC

**Comment by squeirozmello** [comment]
Hi!

Can you please send me a message when the problem will be solved!

If you need help developing this api let me know!!

Best regards

**Comment by sstrickx** [comment]
Hi,

I'm unable to reproduce the issue (on my side, it's correctly parsing the date "Feb 4" for INTC).
Which Java version and API version are you using? Do you still get the issue when you try the same thing again?

```
Mar 05, 2015 8:07:02 AM yahoofinance.quotes.QuotesRequest getResult
INFO: Sending request: http://finance.yahoo.com/d/quotes.csv?s=INTC&f=n0sc4x0a0b2sa5sb0b3sb6sl1sk3sd1t1o0p0g0h0v0a2k0j0m3m4sj2sss1sj1sf6sr1q0d0y0e0e7e9e8r0r5p6p5b4s6j4t8&e=.csv
Mar 05, 2015 8:07:04 AM yahoofinance.quotes.QuotesRequest getResult
INFO: Parsing CSV line: \"Intel Corporation\",\"INTC\",\"USD\",\"NasdaqNM\",34.29,34.29,\"INTC\",200,\"INTC\",34.10,34.10,\"INTC\",300,\"INTC\",34.12,\"INTC\",897,216,\"INTC\",\"3/4/2015\",\"4:00pm\",33.86,34.095,33.72,34.41,23005798,28475300,37.90,24.38,34.4629,34.7906,\"INTC\",  4,736,000,000,\"INTC\",\"INTC\",-,\"INTC\",161.6B,\"INTC\",  4,729,180,000,\"INTC\",\"Mar  1\",\"Feb  4\",0.915,2.68,2.31,2.38,0.55,2.60,14.76,1.59,2.90,2.89,11.766,55.870B,24.191B,37.27
Mar 05, 2015 8:07:04 AM yahoofinance.quotes.QuotesRequest getResult
INFO: Sending request: http://finance.yahoo.com/d/quotes.csv?s=INTC&f=n0sc4x0a0b2sa5sb0b3sb6sl1sk3sd1t1o0p0g0h0v0a2k0j0m3m4sj2sss1sj1sf6sr1q0d0y0e0e7e9e8r0r5p6p5b4s6j4t8&e=.csv
Mar 05, 2015 8:07:05 AM yahoofinance.quotes.QuotesRequest getResult
INFO: Parsing CSV line: \"Intel Corporation\",\"INTC\",\"USD\",\"NasdaqNM\",34.29,34.29,\"INTC\",200,\"INTC\",34.10,34.10,\"INTC\",300,\"INTC\",34.12,\"INTC\",897,216,\"INTC\",\"3/4/2015\",\"4:00pm\",33.86,34.095,33.72,34.41,23005798,28475300,37.90,24.38,34.4629,34.7906,\"INTC\",  4,736,000,000,\"INTC\",\"INTC\",-,\"INTC\",161.6B,\"INTC\",  4,729,180,000,\"INTC\",\"Mar  1\",\"Feb  4\",0.915,2.68,2.31,2.38,0.55,2.60,14.76,1.59,2.90,2.89,11.766,55.870B,24.191B,37.27
Mar 05, 2015 8:07:05 AM yahoofinance.Stock update
INTC
--------------------------------
symbol: INTC
INFO: Updated Stock with symbol: INTC
name: Intel Corporation
currency: USD
stockExchange: NasdaqNM
quote: Ask: 34.29, Bid: 34.10, Price: 34.12, Prev close: 34.095
stats: EPS: 2.31, PE: 14.76, PEG: 1.59
dividend: Pay date: Sun Mar 01 06:00:00 CET 2015, Ex date: Wed Feb 04 06:00:00 CET 2015, Annual yield: 2.68%
history: null
--------------------------------
```

**Comment by squeirozmello** [comment]
Hi,

I am using Java 1.7.0_51 and the API is version 1.2.1.

I still have this error..

Thanks!

Sebastião Queiroz e Mello

No dia 05/03/2015, às 08:23, Stijn Strickx <notifications@github.com> escreveu:

**Comment by sstrickx** [comment]
Hi,

Just to let you know that I've most likely found the issue.
People with a different default locale than US or UK probably experience this issue.
I'll provide a fix soon.
