### ISSUE TITLE
Earnings Date

### ISSUE THREAD

**Issue by ashishpande** [sstrickx/yahoofinance-api#98]
I cannot find the earnings date in the API. Please can you add that.

**Comment by sstrickx** [comment]
Hi, the next earnings date is not available from the Yahoo Finanace API.
I'll see what I can do to find this information.

**Comment by ashishpande** [comment]
Thanks you!

**Comment by ashishpande** [comment]
This issue is resolved thank you very much.

**Comment by peternees** [comment]
Can this issue be reopenend? This would be nice to fix.. 

An example is VRTX. https://query1.finance.yahoo.com/v7/finance/quote?symbols=VRTX contains 
"earningsTimestamp":1651766460,
"earningsTimestampStart":1658919540,
"earningsTimestampEnd":1659355200

**Comment by peternees** [comment]
I've made the following change (locally) to StockQuotesQuery1V7Request.getStats(JsonNode node) 
```
            Calendar earningsTimestamp = null;
            if (node.has("earningsTimestamp")) {
                earningsTimestamp = Utils.unixToCalendar(node.get("earningsTimestamp").asLong());
                stats.setEarningsAnnouncement(earningsTimestamp);
            }
            if (node.has("earningsTimestampStart")) {
                Calendar earningsTimestampStart = Utils.unixToCalendar(node.get("earningsTimestampStart").asLong());
                if (earningsTimestamp == null || earningsTimestampStart.after(earningsTimestamp)) {
                    stats.setEarningsAnnouncement(earningsTimestampStart);
                }
            }
```
