### ISSUE TITLE
Historical dividend information

### ISSUE THREAD

**Issue by retiredracer** [sstrickx/yahoofinance-api#99]
Is it possible to retrieve historical dividend information (e.g, exDate and value) for a time frame?

I can't quite see how to do that in the current API.

But in general this library is really cool.

**Comment by sstrickx** [comment]
Hi, I'm sorry, but historical dividend information is not available from the Yahoo Finance API.
If I can find a good source, I might add it to version 4.

**Comment by retiredracer** [comment]
Actually, I found it....

Easy to implement.  The URL to use is the same for the historical stock quotes (e.g., 'query1.finance...').

Just add the query parameter 'events=div' and keep the 'period1' and 'period2' parameters the same.

I think if you just (as a hack) clone the 'HistoricalQuotes2Request' class as a HistoricalDividendsRequest and change the URL generation logic to add the 'events=div' parameter, you're good to go.

Then just augment the Stock class to include a 'getHistoricalDividends()' method.  Bada Bing.

**Comment by sstrickx** [comment]
Oh right, that seems to work. I'll keep the issue open.

**Comment by retiredracer** [comment]
Excellent!  Thanks.  I'll repull the library and use the official version vs. my hack....
